### ISSUE TITLE
Adding mode to component type also adds it to implementation (sometimes)

### ISSUE THREAD

**Issue by lwrage** [osate/osate-ge#167] opened 2016-08-25 14:17 UTC
In the last AADL course someone added a mode to a system type using the graphical editor. In the AADL text this mode was added to the component type AND the component implementation resulting in an invalid model. (OSATE 2.2.1 vfinal)

**Comment by philip-alldredge** [comment] 2016-08-25 15:19
Is there a way to reproduce this? I haven't seen anything like this before and I am unable to reproduce the issue.

**Comment by lwrage** [comment] 2016-08-25 16:42
No, it only happened on one machine, but it was reproducible there. I think
the user then closed and re-opened  the graphical editor to get correct
behavior back.

**Comment by philip-alldredge** [comment] 2016-08-25 17:31
After a review of the source, the cause of the issue is not immediately apparent.  The graphical editor just calls createOwnedMode() on the classifier when creating a mode.  

As much as I would like to get to the bottom of this, it will not be fixable unless it can be reproduced. Recommend closing until it can be reproduced.

On a related note, the editor should probably stop the user from creating a mode in a component implementation if the type has modes. I have created a separate issue #168 to track that enhancement.

**Comment by philip-alldredge** [comment] 2017-02-24 01:33
Closing since we are unable to reproduce the issue.

**Closed by philip-alldredge** 2017-02-24 01:33 UTC
