### ISSUE TITLE
Desired Feature:  Better Font for Labels

### ISSUE THREAD

**Issue by brlarson** [osate/osate-ge#9] opened 2014-05-30 17:23 UTC
The "jaggies" in the labels makes them hard to read, and look bad when enlarged.

Use a better font labels.

Control of font size will be an added bonus.

**Comment by philip-alldredge** [comment] 2016-07-01 21:00
Closing. I agree it would be helpful. Some of the "jaggies" are caused by the underlying library. In general font issues will be revisiting when handling #151.

**Closed by philip-alldredge** 2016-07-01 21:00 UTC
Labels: enhancement
