### ISSUE TITLE
Flow implementation construction (mis)behaviors?

### ISSUE THREAD

**Issue by jjhudak** [osate/osate-ge#178] opened 2016-10-11 21:50 UTC
An observation: if one chooses a flow spec, and then quits without clicking on the path components, an incorrect flow path is put into the aadl txt. One has to go to the txt and manually delete it.  The flow path is puts into the text is: feature1->feature1->feature2;
The parser will immediately flag that as an incorrect statement.

 observation:
Assume a correct flow implementation is constructed graphically and one wishes to edit it, if the top level flow spec is (re)chosen, and a new path is built, again, piece by piece, when completed, if one looks at the text, there will be two flow implementations, each with the same name, and the parser will flag the duplication.  I think it would be better if the same flow spec is chosen, the existing one is removed or?

observation:

The only way to edit a flow implementation (when done graphically) is to delete the existing (in the text) and start over?  There is no option (that I can find) to modify parts of the flow implementation graphically.  True?

**Comment by philip-alldredge** [comment] 2016-10-11 22:27
Thanks for reporting this. It is the intention that the flow implementation created should match that which is shown in the window. I'll look into why the created flow implementation has the extra "feature1" in it. However, this only happens when OK is selected.  If Canceled is selected or the window is closed, no feature is created. 

Flow implementations and end to end flow specifications can be modified by right clicking on the component implementation and selecting "Edit Flows...". The reason the graphical editor doesn't replace the flow implementation is that the AADL standard allows multiple flow implementations for a single flow specification. The parser should not flag it as an error. However the graphical editor doesn't fully support visualizing multiple flow implementations based on the same flow spec. See #133.

**Comment by jjhudak** [comment] 2016-10-12 15:06
Hi Phil:
see embedded comments

**Comment by philip-alldredge** [comment] 2016-10-12 15:54
The issue is that it is creating a flow that has an additional elements that weren't selected by the user. In your example, the middle "feature1". 

Creating a flow path without a detailed implementation should not be an error. It is legal that flow paths are allow to simply connect input features and output features without anything in between. See AADL V2.1 10.2 L(6) and (3)

Much to my frustration, flow implementations do not have names which are guaranteed to be unique. The flow identifier must match that of a flow specification and there may be multiple flow implementations with the same name. See AADL V2.1 10.2 (N1).

**Comment by philip-alldredge** [comment] 2016-11-01 15:18
Closing. Flow paths are not required to have segments. The serialization issue is an issue with osate2-core and has been added to its issue tracker.

**Closed by philip-alldredge** 2016-11-01 15:18 UTC
Labels: bug
