### ISSUE TITLE
Renaming Diagrams

### ISSUE THREAD

**Issue by dpgluch** [osate/osate-ge#310] opened 2018-02-28 21:30 UTC
I was creating multiple diagrams for the a system implementation "MyCar.CruiseControlTasks," one for the bindings and one overall perspective of just basically components and data flow. I was creating a third for looking only at bus access and decided to rename the binding diagram that I created earlier. Nominally, the diagrams have the same core name with numbers in parentheses.  After renaming, the latter two diagrams became unreadable. However, the renamed binding diagram is fine.

Perhaps renaming is not supported?  It would be useful but is not critical, since one can export the diagram and name it as needed for clarity.

Thanks,
Dave Gluch
dpg@sei.cmu.edu

**Comment by philip-alldredge** [comment] 2018-02-28 21:43
What do you mean, "the latter two diagrams became unreadable"? Was there an error in the error log? The intention is for the user to be able to name the diagrams whatever they prefer.

**Comment by dpgluch** [comment] 2018-03-01 16:34
Phil,

Thanks for getting back to me on this.  Sorry, I did not grab the error message, trying to get ready for a course delivery next week.  But one diagram would not open and the other was fragmented (could not make out any structure or interact with it).  However, I have tried to repeat the error but have not had it reoccur.  I did the rename with the pull down menu not when I created the diagram.

I will let you know if occurs again and will capture the error message/log.

By-the-way, I think you have done a very good job with the editor. This is one of the first issues I have had with it.

Thanks again,

Dave

**Comment by philip-alldredge** [comment] 2018-03-01 21:50
Yes, please let us know if you encounter the issue again. Screenshots of the error and the diagrams(if possible) would be helpful. I'll leave this open for a while, but I'll close it if we aren't able to reproduce it in the near future.

Thanks for the positive feedback. We appreciate it. I'm hopeful that the test suite @RyanMcilnay is working on will help us improve to reliability of the tool going forward.

**Comment by philip-alldredge** [comment] 2018-04-12 18:34
Closing. Unable to reproduce.

**Closed by philip-alldredge** 2018-04-12 18:34 UTC
Labels: bug, not reproducible
