### ISSUE TITLE
AADL Diagram shows differently on different machines

### ISSUE THREAD

**Issue by janetlj** [osate/osate-ge#173] opened 2016-09-13 21:40 UTC
Issue: The same .aadl_diagram file shows differently on two different computers: 
In one computer the text is getting cropped or overlapped (e.g., the names of two ports overlap with each other, or the beginning part of a bus name getting cropped), while in the other computer the text for AADL elements are fully displayed. 

It can occur to files of smaller size (e.g., 30KB) or bigger size (e.g., 90KB).

This affects our ability to demo/deliver the diagrams from Subversion for customer review.

Both computers have the same version of OSATE installed (OSATE2 v2.2.1vfinal obtained from http://www.aadl.info/aadl/osate/stable/2.2.1-old/). Both computers use Windows 7 Enterprise 64-bit Operating System.

**Comment by philip-alldredge** [comment] 2016-09-26 21:28
Janet,
I have found several text rendering issues. I'm tracking that in issue #175. 

I've been able to produce results that are close to the images that you sent me, but I need your help to confirm whether any of the issues I've identified is the cause for your issues. 

1-) Can you email me an image of the problem. One correctly sized and one incorrectly sized. These can be cropped and similar to the ones you sent me previously. However, I need them to be generated by the "Export Diagram" feature. Right click in the diagram and select Export Diagram. Save as PNG with a Scale-factor of 1.0. This will help eliminate some of the variables.
2-) On the machines that you take the image from, record the text scaling setting. To view that setting: From the Start menu open the Control Panel. Choose Appearance and Personalization then click Make text and other items bigger or smaller. 

Thank you

**Comment by philip-alldredge** [comment] 2016-11-10 16:31
Believe this is fixed. Closing.

**Closed** 2016-11-18 19:10 UTC
Labels: bug
