### ISSUE TITLE
Thread deadlock when using GE

### ISSUE THREAD

**Issue by lwrage** [osate/osate-ge#100] opened 2014-12-11 13:36 UTC
In a tutorial one of the participants encountered a deadlock. OSATE freezes and needs to be killed and restarted. From the thread dump it seems that it's a problem in the synchronization of between textual and graphical editor.
Thread dump: https://gist.github.com/lwrage/5465d9cd3e2b1f28a437
See line 294ff in the thread dump for the deadlock information

I had another OSATE user complaining about deadlocks but he didn't produce a thread dump so I don't know if he saw the same issue. So far I haven't been able to reproduce the issue, but I think it's severe enough that it needs to addressed.

**Comment by philip-alldredge** [comment] 2015-01-05 15:23
I was only able to reproduce the deadlock once. However, 19380da164f0eab46601ee3bb7167ab172ecf61a includes a change that is intended to fix the issue.I am closing the issue. Please re-open if it reoccurs.

**Closed by philip-alldredge** 2015-01-05 15:23 UTC
Labels: bug
