### ISSUE TITLE
Missing window decorations for flow editing dialogs

### ISSUE THREAD

**Issue by lwrage** [osate/osate-ge#119] opened 2015-09-14 17:16 UTC
When I use the toolbar items "create flow implementation" and "create end to end flow specification" I get dialogs without title bar or border. The dialog windows are at the top left of the screen and can't be moved or resized.
This is with OSATE 2.1.2 on Linux (Kubuntu 15.4)

**Comment by philip-alldredge** [comment] 2015-09-14 21:06
Ryan has committed a change that we hope fixes the problem. We don't have a Linux test environment. Can you test it and let us know if the fix works?

**Comment by lwrage** [comment] 2015-09-15 14:18
The change only addresses the placement. There are still no window decorations.(Other dialogs, e.g., edit flows; set extended classifier; bind, work as expected) This is what it looks like:

![snapshot1](https://cloud.githubusercontent.com/assets/750311/9878751/4be01f8a-5b92-11e5-9960-e39a4a314b21.png)

**Comment by philip-alldredge** [comment] 2015-09-15 14:42
Okay. Thanks for the screenshot. That helps a lot.

I'll submit a fix soon.

**Comment by philip-alldredge** [comment] 2015-09-15 14:54
The issue was caused by how the ON_TOP hint is implemented on linux.

The fix has been merged in 70fefe8c33ee51472e9a45f6968ae69fdc6f1c35.

We are confident this will resolve the issue. Reopen if the problem reoccurs.

**Closed by philip-alldredge** 2015-09-15 14:54 UTC

**Comment by lwrage** [comment] 2015-09-15 15:14
It's better now. There's a title bar so it can be moved around. It's not resizable, though.

![snapshot1](https://cloud.githubusercontent.com/assets/750311/9880626/62a02c6c-5b9a-11e5-9267-5cc0db4427b8.png)

**Comment by philip-alldredge** [comment] 2015-09-15 15:30
Okay great. I've created a separate issue to track the re-sizing of various dialogs.

**Comment by lwrage** [comment] 2015-09-15 15:37
I just tried to add SWT.RESIZE. That makes the dialog resizable, at least on Kubuntu.

**Comment by philip-alldredge** [comment] 2015-09-15 15:51
Yes, that would make the window resizeable. Additionally, we may want to consider setting appropriate minimum sizes for the dialogs. Issue #120 will handle that issue. Feel free to merge your change in if needed sooner.
