### ISSUE TITLE
Rendering features in a feature group

### ISSUE THREAD

**Issue by jjhudak** [osate/osate-ge#157] opened 2016-05-19 20:04 UTC
A set of features contained in a feature group that contains 'inverse of' another FG are not shown graphically.  I don't know if this is a bug, or functions as intended.  My expectation is that the features of the FG defined as 'inverse of'  should be rendered.  
I have kept the default setting/behavior of the Classifier_Match rule.
Below are two test cases.  

For case #1, showing the graphical view of ControllerDataOut displays the two out data ports.  The graphical view of the ControllerDataIn (which is is the 'inverse of' ControllerDataOut, results in an empty rectangular box.

Test case #2 ControllerDataIn2 does, with the ports explicitly defined and the directions defined, does show the ports in the graphical view.
-------- Code follows -------------
package test
public
-- Case #1 ----
    feature group ControllerDataOut
    features
        MyData1: out data port;
        MyData2: out data port; 
end ControllerDataOut;

feature group ControllerDataIn
    inverse of ControllerDataOut
    end ControllerDataIn;

---- Case #2  ------------
    feature group ControllerDataOut2
    features
        MyData1: out data port;
        MyData2: out data port; 
end ControllerDataOut2;

feature group ControllerDataIn2
        features
        MyData1: in data port;
        MyData2: in data port;  
    inverse of ControllerDataOut2
    end ControllerDataIn2;  
end test;

**Comment by philip-alldredge** [comment] 2016-05-19 20:52
This is functioning as intended.  I'll mark this as a feature request to be considered when implementing future enhancements. The change would be to calculate the inverse of the features and display them whenever inverse of is used and the feature group type does not contain any explicitly defined features.  

Is the use case for this for visualization purposes or is there another use case? I'm afraid it would likely be considered a nice-to-have feature but would likely be prioritized behind others currently in the works.

**Comment by jjhudak** [comment] 2016-05-20 16:05
Hi Phil:
Thanks for the reply.  I can understand that there are other more important issues to address, but I am not sure this is a ‘nice to have.’(I don’t think I’d put it at the bottom of the list in any case)….I think that if the semantics of ‘inverse of’ is a short hand way of including the content of the reference object, then one’s expectation upon visualizing the object would be to see the contents.  It does display properly when the FG is attached to a system/device, so the need to have it ‘fixed’ as submitted is not that important.
Thank  you for clarifying that it is working as intended – that sets my expectation.
Best regards,

John

**Comment by philip-alldredge** [comment] 2016-05-20 16:57
John,
Thanks for the feedback. Perhaps nice-to-have was a poor choice of words. I'm including some additional explanation and notes below for you but also as a reference when/if the feature is implemented.

Except for when it is necessary for graphical editing capabilities, the editor *usually* avoids adding graphical elements for things that aren't part of the declarative model. Additionally, explicitly defining the inverse features graphically is problematic because they need to be in the same order in the AADL specification.

The implementation would need to indicate that the features being displayed aren't actually part of the feature group type declaration. That would be important because adding a feature would result in the implicit features disappearing since the user is specifying the features explicitly. 

On this same topic, I believe it would be helpful to indicate to the user that the feature group type has an inverse of clause. This is currently not represented graphically.

**Comment by philip-alldredge** [comment] 2018-04-24 18:52
Closing. Won't fix for now.

**Closed by philip-alldredge** 2018-04-24 18:52 UTC
Labels: request
