### ISSUE TITLE
Flow selection drop down disabled (Linux)

### ISSUE THREAD

**Issue by lwrage** [osate/osate-ge#121] opened 2015-09-15 19:43 UTC
The drop down to select a flow doesn't do anything, it seems to be completely disabled.
This is with OSATE 2.1.2 on Kubuntu 15.04 (it works in Windows)

![snapshot1](https://cloud.githubusercontent.com/assets/750311/9887915/2b35282e-5bc0-11e5-84ef-9473b13bc79f.png)

**Comment by lwrage** [comment] 2015-09-16 14:18
Actually, sometimes it's enabled, sometimes not. I haven't yet found a pattern.

**Comment by philip-alldredge** [comment] 2015-09-23 17:52
We will need to setup a linux development environment to try to troubleshoot the issue.

**Comment by lwrage** [comment] 2015-09-28 19:42
The bug seems not to be in the OSATE graphical editor. It also happens in the ecore editor. Also, if I switch mode and flow dropdowns, then it's the mode dropdown that doesn't work.

**Comment by lwrage** [comment] 2015-09-29 16:26
The issue occurs on Kubuntu 15.04 but NOT on Ubuntu 14.04. I assume it's a KDE problem.

**Comment by lwrage** [comment] 2015-10-02 16:51
Proposed fix committed in 83bee931c41a1e17e7c31c6864285a8657c548d2
It seems that the rightmost dynamic dropdown in the toolbar doesn't work. The workaround adds a third dynamic dropdown, which is invisible. It works on Kubuntu 15.04.

**Comment by philip-alldredge** [comment] 2015-10-08 13:21
Since the workaround seems to work. Closing for now. Eventually, it would nice to remove the workaround  when the root cause is fixed.

**Closed by philip-alldredge** 2015-10-08 13:21 UTC
Labels: bug
