### ISSUE TITLE
Can't add subcomponent flow to flow implementation (sometimes)

### ISSUE THREAD

**Issue by lwrage** [osate/osate-ge#166] opened 2016-08-25 14:15 UTC
Sometimes it is not possible to add a subcomponent flow to a flow implementation using the tool. When the flow is selected, the tool reports an error message along the lines "select a subcomponent, subcomponent flow, etc" so the selection is not recognized as a flow though a subcomponent.
Closing and reopening the graphical editor usually fixes the issue. It may be related to having unsaved changes in multiple open graphical editors. I haven't found a way to reliably reproduce the issue.
In the last AADL course we used the graphical editor for creating models and encountered this several times. This is with OSATE 2.2.1 vfinal.

**Comment by philip-alldredge** [comment] 2016-10-04 13:58
After attempting to reproduce the issue, I have been unable to reproduce this bug reliably. 

One situation that could be the cause is that elements must be selected one at a time. If multiple diagram elements are selected(by holding down shift or CTRL), then those selections are ignored. I did this by mistake once and was confused by the message. I have added a warning message when multiple diagram elements are selected. 

Does it seem plausible that this is the cause? In my case I started holding down the shift key without realizing it.

In any case, I'm inclined to close the issue unless it can be reproduced.

**Comment by lwrage** [comment] 2016-10-04 17:07
I definitely didn't hold down the shift key when it happened. Also, during
the AADL course it happened to almost everybody at some time. I have the
impression that it happens after making many edits without closing the
graphical editor.

**Comment by philip-alldredge** [comment] 2016-10-04 17:08
Okay. I'll keep trying to find a way to reproduce it for a bit longer.

**Comment by philip-alldredge** [comment] 2016-10-04 20:13
Were multiple packages being used when the issue occurred? I've been able to reproduce the issue with a single package but it seems to occur more often when multiple packages are being used. I have a general idea what is happening in both cases.

**Comment by philip-alldredge** [comment] 2016-10-04 20:57
I believe the latest change fixes the issue.

**Closed by philip-alldredge** 2016-10-04 20:57 UTC
Labels: bug
